# Generated by Django 5.1 on 2024-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='two_step_auth',
            field=models.BooleanField(default=False),
        ),
    ]
